### ISSUE TITLE
version state files

### ISSUE THREAD

**Issue by kain88-de** [datreant/datreant#108]
With new changes currently discussed in #100 I think it's possible that a change in the statefile format might come soon. I don't expect this to be the last one. Especially since we are still figuring out what recommended workflows should be. To ease transitions for users I think we should version state files.

This would allow us to write code to update treants and find out when a Treant was created with a newer version of the library then is currently used.

**Comment by dotsdl** [comment]
Agreed, this will rear its head occasionally, so we should at the very least include version entries in the dict of each JSON file for each level (top-level is datreant, lower levels can be packages like mdsynthesis). This problem was previously identified as something that could be really painful later in #18, but was dropped at the time because getting into a working state was more important than future-proofing at the time.

What a scheme for helping old Treants move forward in time to current schema is probably a bit of a project, and it runs into issues of performance, too, since we don't want to slow the use of Treants down by whatever machinery for checking versioning we use. I couldn't think of a clean way of balancing performance with this last I thought of it.

We could for the moment just introduce a `version` key in the JSON spec and insert the `datreant.core` version used to create the state file. Would this work as a start?

**Comment by kain88-de** [comment]
I would give a version number to the JSON spec. I assume we will have more releases of datreant.core then actuall changes to the JSON spec.

**Comment by kain88-de** [comment]
> What a scheme for helping old Treants move forward in time to current schema is probably a bit of a project, and it runs into issues of performance, too, since we don't want to slow the use of Treants down by whatever machinery for checking versioning we use. I couldn't think of a clean way of balancing performance with this last I thought of it.

I agree that is another project for itself. As an idea about the performance. Maybe it's OK if we only run the update when the treant is actually accessed.

Btw how/when should a version check be done? We would need to read the file for that.

**Comment by kain88-de** [comment]
So for the performance. We could by default not do an update. Updates have to be done by the user with something like `dtr.update(path)` to update any treant found in path or below.

**Comment by dotsdl** [comment]
Closing, as we've simplified how state is structured for Treants in 1.0.0, and don't plan to change these structures. We've left ourseles room to add new ones with the new mechanism.
