### ISSUE TITLE
1.0.0 Release

### ISSUE THREAD

**Issue by richardjgowers** [datreant/datreant#159]
I'm needing to use datreant for something in production, but I want it to use "new" style treants from the start, these are only in 0.8 onwards right?

Is it possible to release the current state on conda?

**Comment by dotsdl** [comment]
Hey @richardjgowers, the "new" style Treants will only show up in 0.8 onwards, correct. I think it's time we cut the release (I'm starting to use the 0.8-dev branch myself for work), so I'm going to add this to the docket for this weekend. This will include a conversion function/script for "old" Treants, as well as a blog post/mailing list announcement explaining the changes.

**Comment by richardjgowers** [comment]
@dotsdl yeah I'm guilty of also using the dev branch myself for a while, but I'm finally getting ready to ship something so I need this packaged :D Happy to help out over the weekend

**Comment by dotsdl** [comment]
This hasn't fallen off my radar, but life got in the way this last weekend. Shooting again for this coming weekend. The list of todos:

- [ ] blog post on what the changes are (there are big ones, and they are many), and the rationale
- [ ] change package name to `datreant` (we'll still keep a `datreant.core` submodule to maintain compatibility with existing code that imports that way)
- [ ] create new `datreant` package on PyPI (can't use old one since the name has changed)

Creating a new package on PyPI will avoid users inadvertently upgrading with a simple `pip install datreant.core`, but after the initial 0.8.0 release we'll need to:
- [ ] deprecate the old `datreant.*` packages on PyPI
- [ ] provide conversion scripts as part of `datreant` for converting old-style Treants to new-style ones.

Does this sound reasonable @richardjgowers, @kain88-de? I know this has been a long process with many iterations, but part of the challenge is not disrupting the work of users while also being able to make really disruptive progress with limited time devoted to development.

**Comment by kain88-de** [comment]
there needs to be a mini-release of mdsynthesis fixing the datreant version. If we don't do this new user will have a non-working version of mdsynthesis only.

Also are there dependencies on GitHub of the package? Maybe a warning would be nice.

I would also like to keep the `datreant.core` is possible. I use that in *soo many* of my own scripts.

**Comment by dotsdl** [comment]
I've pushed the name change to `develop`. Been hard to eke out bits of time for this so just trying to knock it out. 

@kain88-de, if you have a moment could you make the conda packaging work without the namespace package? I think this should just require some trimming...

**Comment by kain88-de** [comment]
Making the datreant package work will be a bit tricky. For one the namespace package published on conda-forge has the version number 1.0 [anaconda.org](https://anaconda.org/conda-forge/datreant). Any update to that package needs a larger version number.  I do currently not know anymore why I set the version to 1.0 when I created the package. 

I could update the namespace package to contain the actual implementation. But this will break `datreant.core` which depends on `datreant`. This should also be fixable by making a new minor release and fixing the datreant dependency version. 

All of this is doable but highly suspective. It might break in unforeseen ways. 

Another issue is that on pip the update now has to be explicit. The user will have to first remove datreant.core and other datreant dependent packages before he can install `datreant` to do an upgrade. And of course, we need updates to all our minor packages to ensure that installing `datreant.data` in an environment that has `datreant` installed will throw an error. Is it even possible to declare conflicts in setup.py?

**Comment by kain88-de** [comment]
A solution for pip might be to release an explicit datreant namespace package first and then use dependency binding to a specific version similar to a solution on conda. But again this seems hacky and might not work.

**Comment by richardjgowers** [comment]
Couldn't you just increment the build number for the conda release to
become "higher"?

**Comment by kain88-de** [comment]
A version number `1.0-0` is still higher than `0.8-1`.  The version number always trumps the build number.

**Comment by richardjgowers** [comment]
Oh right, I forgot that we're still subzero with core.  Is there anything obvious we're planning on breaking that would stop us calling 0.8 1.0?

**Comment by kain88-de** [comment]
This still wouldn't fix the installation problem on pip I outlined above. This is because on pip a datreant package doesn't exist yet. If we now add one and a user would install `datreant` and `datreant.core` he will have a messy and maybe broken python installation.

**Comment by dotsdl** [comment]
I honestly don't think there's a clean way to proceed here. This is part of why this process has taken so long on my end, since we don't want to make things hard for users, but I think there's just going to be a (hopefully short) painful period no matter what we do. The namespace packaging seemed like a good idea at the time, but certainly not in hindsight.

I think we just have to be upfront with the breakage before we create it. Pushing the PyPI package is easy and I believe the work to be done on 0.8. Watch for a PR on the [datreant website repo](https://github.com/datreant/datreant.github.io) from me with a blog post explaining the transition and how to mitigate it for users.

**Comment by kain88-de** [comment]
I don't mind the mitigation issue. But removing the namespace package has the potential to break user install for years to come with perfectly valid pip installations. There is nothing keeping one from running `pip install datreant` and `pip install datreant.data` in any order and the two have the possibility to break a python installation?

What happens to people who just run `pip install --upgrade` when they have datreant installed? We can't expect that they read the blog posts explaining the update procedure.

**Comment by dotsdl** [comment]
I've never actually done it before, but could we add custom code somewhere in `setup.py` that removes `datreant.core` and `datreant.data`, if present, before proceeding?

**Comment by kain88-de** [comment]
that seems like more trouble then it's worth. This change would need to work both ways. 
This is mainly a problem because pip doesn't have proper dependency resolution. We could make a version pinning of datreant.data to an earlier version of `datreant`. This will give package managers enough information and can be made to work with conda given correct version numbers. People relying on pip will then have to live with the breakage.

My best solution right now is

- make a new datreant.data minor release pinning to `datreant<=0.8`
- making a new mdsynthesis minor release pinning to `datreant<=0.8`
- release datreant 1.0
- release mdsynthesis 1.0
- update conda-package with dependency information.

**Comment by dotsdl** [comment]
Minor release od datreant.data has been [made](https://github.com/datreant/datreant.data/releases/tag/release-0.7.1). This will be the last release of datreant.data, and it is tied to datreant.core 0.7.1.

**Comment by dotsdl** [comment]
Since we actually have MDSynthesis working with the functionality formerly provided by `datreant.data` already built in, I don't think we need to release a minor release linking it to `datreant.data`. Let's proceed with releasing `datreant` 0.8.0 (or 1.0, if we prefer that) and then release MDSynthesis 1.0.

Something that we still need is a converter script for old Treants to new ones. This is "just" a lot of JSON handling, but needs to be done yet. Unfortunately not glamorous work.

**Comment by richardjgowers** [comment]
@dotsdl for a converter script, would it would just to create a class `OldTreant` which is the old discovery + treant class, then squeeze that into the new Treant class, then save?  So read it all into memory with the old mechanisms, dump it back to disk with new mechanisms, then tidy up?  I can have a crack at it if it's just that

**Comment by kain88-de** [comment]
@richardjgowers yes that is essentially it. Take in a `Treant.*.json` file and create a new  Treant object. Something as simple as the following might even be enough.

```python
def convert(folder):
    json_file = glob(path.join(folder, 'Treant*'))[0]
    with open(json_file) as fh:
        old = json.load(fh)
    Treant(folder, categories=old['categories'], tags=old['tags'])
```

Then we need some recursive search algorithm that looks for the old Treant files.

**Comment by dotsdl** [comment]
Yup, what you have @kain88-de is exactly the route I'd take. I recommend we take the route of previous converter scripts where the script takes a single Treant file as input and does essentially what @kain88-de has written there. We'll have a similar script packaged up in MDSynthesis for that release.

A user can then use whatever means they like, such as:

```bash
for i in $(find --name Treant.*.json)
do
datreant_08to10.py $i
done
```
to convert their Treants.

**Comment by kaceyreidy** [comment]
@kain88-de What is `path` in your `convert` function?

**Comment by kain88-de** [comment]
The path sub module from os. You can do `from os import path `.

**Comment by kain88-de** [comment]
Please keep in mind the function might be buggy. I wrote this at the top of my head.

**Comment by dotsdl** [comment]
Thanks everyone. After many months (more like years...) we finally did it. Thanks for all your efforts in pushing this project forward, as well as your patience with me as the perennial bottleneck. Looking forward to `datreant` working for us a simple, dependable, and fast package for manipulating filesystems for years to come. Cheers!

**Comment by kain88-de** [comment]
@dotsdl the conda-forge builds and releases are all updated. All old versions of dependencies have new builds that specify the datreant namespace package to be below or equal to version 1.0. This shouldn't break too many user installations now. Did you do something similar for the pypi releases of the dependencies?
