### ISSUE TITLE
Make dict-like functions generators

### ISSUE THREAD

**Issue by richardjgowers** [datreant/datreant#170]
Originally from #169 

For py3-ness things like `.keys/.values/.items` should return generators.

Though maybe it's worth seeing if it is actually possible to pull the contents of a tag file in a generator like manner

**Comment by dotsdl** [comment]
I think the trouble here is exactly as you mention: you can't parse JSON piecemeal to my knowledge. There isn't much point to use generators in this case since it would actually yield no benefit at the cost of some interactive usability.

This is even true for `AggTags` and `AggCategories`, since we still need to parse *all* Treant files to know what's present in `.all` or `.any` cases.

**Comment by richardjgowers** [comment]
Yeah ok, that's fair I guess
