### ISSUE TITLE
allow all comparible objects in categories

### ISSUE THREAD

**Issue by kain88-de** [datreant/datreant#95]
The following code files complaining that only `string, floats and ints` are allowed to be used.

``` python
treant = dtr.Treant('path', categories={'foo', np.array(5)'})
```

I have a case now where my variable that I want to store is a 3 element array. I can store them individually but it would be nice if the numpy array is allowed directly. It would even argue I should be able to store custom objects as long as a equal definition is defined and it can be stored and read from json.

**Comment by dotsdl** [comment]
@kain88-de I think we might be able to do this, but one of the virtues of `Categories` as they are is that they are single-valued key-value pairs, because when working in aggregate doing things like `groupby` are easy-to-define. 

I hesitate to go the route of having, e.g. lists as a possible value because then using `groupby` becomes much more difficult, and the output of doing `bundle.categories[key]` can become really quite nested. It's akin to a `pandas.DataFrame` with multiple values thrown together as a string or list in a single `dtype=object` column, when instead they'd be more useful as separate columns entirely.

**Comment by kain88-de** [comment]
I don't remember anymore why I wanted to do this. But I think it was something like having a general 'param' key with a list of them. I understand your concerns I'll have to think about this a little bit more.

**Comment by dotsdl** [comment]
Closing, as this is would introduce a lot of complexity into categories and we're planning to keep them restricted going forward. For arbitrary data structures, choose a fileformat that is appropriate and use `datreant` as the filepath interface for working with them, e.g.:

```python
import numpy as np
myarray = np.random.randn(100)

# save it
np.save(treant['arrayfile.npy'].abspath, myarray)

# read it back
read_back = np.load(treant['arrafile.npy'].abspath)
```
